import React from 'react'
import { StyleSheet, Button, ScrollView, Platform, Image, Text, View, TouchableOpacity, TouchableHighlight, Alert, SafeAreaView, Font} from 'react-native'
import firebase from 'react-native-firebase'
import Icon from 'react-native-vector-icons/dist/FontAwesome';

export default class HomePage extends React.Component {
  state =  {  name: '', age: 0, location: '', aboutMe: '', funFact: '', animal: '', selectedHobbies: []}

  componentDidMount() {

    // const uid = auth.currentUser.uid;
    let itemsRef = firebase.database().ref(`/Users/g0zbdloUcVXMAFISgYYE1ptWwKC3/info`);
    // hard coded the friend uid, should be generated by the matching algorithms

    let userName = "";
    let userAge = "";
    let userLocation = "";
    let userMe = "";
    let userFun = "";
    let userAnimal = "";
    let userHobbies = [];

    itemsRef.on('value', snapshot => {
      let data = snapshot.val();
      if (snapshot.hasChild("name")) {
        userName = data.name;
      }
      if (snapshot.hasChild("age")) {
        userAge = data.age;
      } 
      if (snapshot.hasChild("location")) {
        userLocation = data.location;
      } 
      if (snapshot.hasChild("aboutMe")) {
        userMe = data.aboutMe;
      } 
      if (snapshot.hasChild("funFact")) {
        userFun = data.funFact;
      } 
      if (snapshot.hasChild("spiritAnimal")) {
        userAnimal = data.spiritAnimal;
      } 
      if (snapshot.hasChild("selectedHobbies")) {
        userHobbies = data.selectedHobbies;
      } 
      // let items = Object.values(data);
      this.setState({ name:userName, age:userAge, location:userLocation, aboutMe:userMe, funFact:userFun, spiritAnimal:userAnimal, selectedHobbies: userHobbies });
    })
  }
  
  render() {
    return (
      <View
        style={styles.container}>

        <TouchableHighlight
         style={styles.logoButton}
         onPress={() => this.props.navigation.navigate('HobbyPage')}>
          <Image source = {require('../assets/Logo.png')}
            style = {styles.logo} />
        </TouchableHighlight>

        <TouchableHighlight
         style={styles.EventButton}
         onPress={() => this.props.navigation.navigate('EventPage')}>
          <Image source = {require('../assets/People_switch.png')}
            style = {styles.Event} />
        </TouchableHighlight>

        <View style={styles.rectangle}>
        </View>
          

        <Image source = {require('../assets/profile_picture_example.png')}
          style = {styles.profilePicture} />

        <Text style = {styles.profileBioHeader}>
          {this.state.name}, {this.state.age} {"\n"}
          {this.state.location}
        </Text>

        <Text style = {styles.profileBio}>
          {"\n"}
          - rock climbing (5) {"\n"}
          - kayaking (4) {"\n"}
          - basketball (1) {"\n"}
          - tennis (2) {"\n"}
          - mountain biking (2)
        </Text>

        <TouchableHighlight
           style={styles.infoButton}
           onPress={() => this.props.navigation.navigate('UserInfo')}>
           <Icon name="info" size={30} color = '#696969'>
          </Icon>
        </TouchableHighlight>

        <TouchableHighlight
         style={styles.profileButton}
         onPress={() => this.props.navigation.navigate('Profile')}>
         <Icon name="user"  size={30} color = 'gray' style = {styles.profileButtonIcon}>
        </Icon>
        </TouchableHighlight>

        <TouchableHighlight
         style={styles.chatButton}
         onPress={() => this.props.navigation.navigate('Chat')}>
         <Icon name="comments"  size={30} color = 'gray' style = {styles.chatButtonIcon}>
        </Icon>
        </TouchableHighlight>

        <TouchableHighlight
         style={styles.checkButton}
         onPress={() => this.props.navigation.navigate('HomePage')}>
         <Icon name="check-circle"  size={100} color = 'green' style = {styles.checkButtonIcon}>
        </Icon>
        </TouchableHighlight>

        <TouchableHighlight
         style={styles.xButton}
         onPress={() => this.props.navigation.navigate('HomePage')}>
         <Icon name="times-circle"  size={100} color = 'red' style = {styles.xButtonIcon}>
        </Icon>
        </TouchableHighlight>
      </View>
  );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ECECEC',
    alignItems: 'center'
  },
  logo: {
    width: '100%',
    height: '100%',
  },
  logoButton: {
    width: '20%',
    height: '8%',
    position: 'absolute',
    alignItems: 'center',
    top: '8%',
  },
  Event: {
    width: '100%',
    height: '100%',
    resizeMode: "stretch"
  },
  EventButton: {
    width: '20%',
    height: '6%',
    position: 'absolute',
    left: '10%',
    top: '10%',
  },
  profilePicture: {
    width: '52%',
    height: '23%',
    borderRadius: 175.5,
    borderColor: 'black',
    top: '21%',
    borderWidth: 1
  },
  profileButton: {
    position: 'absolute',
    width: '13%',
    height: '5.7%',
    left: '5%',
    top: '4%',
    backgroundColor: '#ECECEC'
  },
  profileButtonIcon: {
    position: 'absolute',
    backgroundColor: '#ECECEC'
  },
  profileBioHeader: {
    position: 'absolute',
    width: '90%',
    height: '25%',
    top: '45%',

    fontFamily: 'Montserrat-Black',
    fontSize: 25,
    lineHeight: 35,
    textAlign: 'center'
  },
  profileBio: {
    position: 'absolute',
    width: '90%',
    height: '25%',
    top: '50%',

    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
    lineHeight: 35,
    textAlign: 'center'
  },
  rectangle: {
    height: '65%',
    width: '95%',
    backgroundColor: '#EBB448',
    opacity: 0.3,
    position: 'absolute', 
    top: '17%',
  },
  chatButton: {
    position: 'absolute',
    width: '13%',
    height: '5.7%',
    right: '0%',
    top: '4%',
    backgroundColor: '#ECECEC'
  },
  chatButtonIcon: {
    position: 'absolute',
    backgroundColor: '#ECECEC'
  },
  checkButton: {
    position: 'absolute',
    width: '26%',
    height: '10.4%',
    right: '10%',
    bottom:'5%',
    backgroundColor: '#ECECEC'
  },
  checkButtonIcon: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: '#ECECEC'
  },
  xButton: {
    position: 'absolute',
    width: '26%',
    height: '10.4%',
    left: '10%',
    bottom:'5%',
    backgroundColor: '#ECECEC'
  },
  xButtonIcon: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: '#ECECEC'
  },
  infoButton: {
    position: 'absolute',
    width: '9%',
    height: '3%',
    right: '7%',
    top: '46%'
  },
});
